/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/review-jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit Review Job
     * @description 202 means the job and its outbox entry are persisted, never that a review ran.
     *
     *     An exact replay returns 200 with the job's real status, because reporting the pinned
     *     acceptance for a job that has already moved on would be a fabricated response.
     */
    post: operations["submit_review_job_v1_review_jobs_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/review-jobs/{job_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Review Job */
    get: operations["read_review_job_v1_review_jobs__job_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/review-jobs/{job_id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cancel Review Job
     * @description A running attempt is asked to stop cooperatively, never killed mid-write.
     */
    post: operations["cancel_review_job_v1_review_jobs__job_id__cancel_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/review-jobs/{job_id}/result": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Read Review Job Result
     * @description 409 until a result is committed; a terminal failure is reported by the status route.
     */
    get: operations["read_review_job_result_v1_review_jobs__job_id__result_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/review-jobs/{job_id}/revisions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Job Revisions */
    get: operations["list_job_revisions_v1_review_jobs__job_id__revisions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/review-jobs/{job_id}/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Job Tasks
     * @description Answered and superseded tasks stay listed, so a stale page can discover why it is.
     */
    get: operations["list_job_tasks_v1_review_jobs__job_id__tasks_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/review-tasks/{task_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Read Task
     * @description Carries the subject name of its own side, so no client re-derives a canonical key.
     */
    get: operations["read_task_v1_review_tasks__task_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/review-tasks/{task_id}/responses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit Task Response
     * @description 200 means the answer is committed; an exact replay returns the same receipt body.
     */
    post: operations["submit_task_response_v1_review_tasks__task_id__responses_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/reviews": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Review */
    post: operations["review_v1_reviews_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/validate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Validate */
    post: operations["validate_v1_validate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * ActorReference
     * @description Server-authored record, never an external credential.
     */
    ActorReference: {
      /** Actor Id */
      actor_id: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "human" | "system" | "model";
      /**
       * Schema Version
       * @default service-v1
       * @constant
       */
      schema_version: "service-v1";
    };
    /** AgentReviewRequest */
    AgentReviewRequest: {
      /** Case Document Uri */
      case_document_uri: string;
      /** Case Id */
      case_id: string;
      /** Criteria Document Uri */
      criteria_document_uri: string;
      field_map?: components["schemas"]["PDFFieldMap"] | null;
      /** Output Pdf Uri */
      output_pdf_uri?: string | null;
      /** Pdf Template Uri */
      pdf_template_uri?: string | null;
    };
    /** AgentReviewRun */
    AgentReviewRun: {
      /**
       * Artifact Status
       * @default not_requested
       * @enum {string}
       */
      artifact_status:
        "not_requested" | "unavailable" | "unsupported_contexts" | "simulated" | "written";
      /** Audit Events */
      audit_events?: components["schemas"]["AuditEvent"][];
      /** Case Id */
      case_id: string;
      case_review?: components["schemas"]["CaseReviewResult"] | null;
      /** Output Pdf Uri */
      output_pdf_uri?: string | null;
      pdf_error?: components["schemas"]["PDFProblem"] | null;
      pdf_result?: components["schemas"]["PDFWriteResult"] | null;
      review?: components["schemas"]["FactorReviewResult"] | null;
      status: components["schemas"]["WorkflowStatus"];
      verification?: components["schemas"]["VerificationReport"] | null;
    };
    /** ArtifactManifest */
    ArtifactManifest: {
      /**
       * Artifact Id
       * Format: uuid
       */
      artifact_id: string;
      /** Content Hash */
      content_hash: string;
      context: components["schemas"]["ComparisonContext"];
      /** Field Ids */
      field_ids: string[];
      /** Field Map Hash */
      field_map_hash: string;
      /**
       * Media Type
       * @default application/pdf
       * @constant
       */
      media_type: "application/pdf";
      /** Page Count */
      page_count: number;
      /**
       * Publication
       * @default local_only
       * @constant
       */
      publication: "local_only";
      /**
       * Schema Version
       * @default service-v1
       * @constant
       */
      schema_version: "service-v1";
      /**
       * Scope
       * @default single_context
       * @constant
       */
      scope: "single_context";
      /** Template Hash */
      template_hash: string;
      /**
       * Verification
       * @default local_writer_reopened
       * @constant
       */
      verification: "local_writer_reopened";
    };
    /** AuditEvent */
    AuditEvent: {
      /** Case Id */
      case_id: string;
      /** Details */
      details?: {
        [key: string]: unknown;
      };
      /** Event Type */
      event_type: string;
      /** Evidence Ids */
      evidence_ids?: string[];
      /** Rule Ids */
      rule_ids?: string[];
      /** Sequence */
      sequence: number;
      /** Status */
      status: string;
      /** Tool */
      tool: string;
    };
    /**
     * CanonicalCase
     * @description Provider-neutral representation of one appraisal review case.
     */
    CanonicalCase: {
      /** Case Id */
      case_id: string;
      /** Fields */
      fields: {
        [key: string]: components["schemas"]["ExtractedField"];
      };
      /**
       * Schema Version
       * @default 0.1.0
       */
      schema_version: string;
      /** Source Versions */
      source_versions?: {
        [key: string]: string;
      };
    };
    /** CaseIdentity */
    CaseIdentity: {
      /** Case Id */
      case_id: string;
      /** District */
      district: string;
      /**
       * Effective Date
       * Format: date
       */
      effective_date: string;
      /** Land Use Category */
      land_use_category: string;
      /** Version */
      version: string;
      /** Zone */
      zone: string;
    };
    /** CaseReviewResult */
    CaseReviewResult: {
      /** Comparisons */
      comparisons: components["schemas"]["FactorReviewResult"][];
      coverage: components["schemas"]["Coverage"];
      /** Findings */
      findings: components["schemas"]["ReviewFinding"][];
      identity: components["schemas"]["CaseIdentity"];
      /**
       * Schema Version
       * @default 2.0
       * @constant
       */
      schema_version: "2.0";
      status: components["schemas"]["EvaluationStatus"];
    };
    /**
     * CheckStatus
     * @enum {string}
     */
    CheckStatus: "pass" | "fail" | "needs_review";
    /** ComparisonContext */
    ComparisonContext: {
      /** Comparable Id */
      comparable_id: string;
      /**
       * Scope
       * @enum {string}
       */
      scope: "regional" | "individual";
      /** Target Id */
      target_id: string;
    };
    /** Coverage */
    Coverage: {
      /** Missing */
      missing: string[];
      /** Required */
      required: string[];
      /** Unsupported */
      unsupported?: string[];
      /** Verified */
      verified: string[];
    };
    /**
     * DocumentReference
     * @description External identity: no caller-selected storage URI or asserted authority.
     */
    DocumentReference: {
      /** Case Id */
      case_id: string;
      /** Content Hash */
      content_hash: string;
      /** Document Id */
      document_id: string;
      /**
       * Purpose
       * @enum {string}
       */
      purpose: "criteria" | "forms" | "reference" | "brief" | "template";
      /**
       * Schema Version
       * @default service-v1
       * @constant
       */
      schema_version: "service-v1";
      /** Version */
      version: string;
    };
    /** EntryProblem */
    EntryProblem: {
      /** Code */
      code: string;
      /** Message */
      message: string;
    };
    /**
     * EntryProblemResponse
     * @description The same JSON envelope used by HTTP and direct invocation.
     */
    EntryProblemResponse: {
      error: components["schemas"]["EntryProblem"];
    };
    /**
     * EvaluationStatus
     * @enum {string}
     */
    EvaluationStatus: "verified" | "needs_review" | "failed";
    /** EvaluationSummary */
    EvaluationSummary: {
      status: components["schemas"]["EvaluationStatus"];
      /** Total Adjustment Percent */
      total_adjustment_percent: number | null;
    };
    /**
     * EvidenceRef
     * @description Location and confidence for a value found in a source document.
     */
    EvidenceRef: {
      /** Block Ids */
      block_ids?: string[];
      /** Bounding Box */
      bounding_box?: [number, number, number, number] | null;
      /** Confidence */
      confidence: number;
      /** Coordinate System */
      coordinate_system?: ("ocr_top_left" | "pdf_bottom_left") | null;
      /** Document Id */
      document_id: string;
      /** Page */
      page: number;
      /** Source File */
      source_file?: string | null;
    };
    /**
     * ExecutionStatus
     * @enum {string}
     */
    ExecutionStatus: "queued" | "running" | "succeeded" | "failed";
    /**
     * ExtractedField
     * @description A normalized field that retains its original representation.
     */
    ExtractedField: {
      /** Evidence */
      evidence?: components["schemas"]["EvidenceRef"][];
      /** Raw Value */
      raw_value: string | null;
      /** Value */
      value: string | number | boolean | null;
    };
    /** FactSideReference */
    FactSideReference: {
      context: components["schemas"]["ComparisonContext"];
      /** Factor Id */
      factor_id: string;
      /** Input Digest */
      input_digest: string;
      /**
       * Schema Version
       * @default service-v1
       * @constant
       */
      schema_version: "service-v1";
      /**
       * Side
       * @enum {string}
       */
      side: "target" | "comparable";
    };
    /** FactorEvaluationResult */
    FactorEvaluationResult: {
      /** Adjustment Percent */
      adjustment_percent?: number | null;
      /** Calculation Trace */
      calculation_trace: string;
      comparable_grade?: components["schemas"]["Grade"] | null;
      /** Factor Id */
      factor_id: string;
      /** Rule Id */
      rule_id?: string | null;
      status: components["schemas"]["EvaluationStatus"];
      target_grade?: components["schemas"]["Grade"] | null;
      /** Warnings */
      warnings?: string[];
    };
    /** FactorReviewResult */
    FactorReviewResult: {
      /** Case Id */
      case_id: string;
      /** Case Version */
      case_version?: string | null;
      context?: components["schemas"]["ComparisonContext"] | null;
      /** Results */
      results: components["schemas"]["FactorEvaluationResult"][];
      /** Rule Set Id */
      rule_set_id: string;
      /** Rule Version */
      rule_version: string;
      /** Source Hashes */
      source_hashes?: {
        [key: string]: string;
      };
      summary: components["schemas"]["EvaluationSummary"];
    };
    /** Finding */
    Finding: {
      /** Actual */
      actual?: unknown;
      /** Evidence */
      evidence?: components["schemas"]["EvidenceRef"][];
      /** Expected */
      expected?: unknown;
      /** Message */
      message: string;
      /** Rule Id */
      rule_id: string;
      /** Rule Version */
      rule_version: string;
      /**
       * Severity
       * @enum {string}
       */
      severity: "info" | "warning" | "error";
      status: components["schemas"]["CheckStatus"];
    };
    /**
     * Grade
     * @enum {string}
     */
    Grade: "excellent" | "slightly_superior" | "normal" | "slightly_inferior" | "inferior";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HumanResponse
     * @description Untrusted command: principal/roles and approval flags are not accepted.
     */
    HumanResponse: {
      action: components["schemas"]["ResponseAction"];
      correction?: components["schemas"]["ValueRevision-Input"] | null;
      /** Expected Version */
      expected_version: number;
      /** Idempotency Key */
      idempotency_key: string;
      /** Result Digest */
      result_digest?: string | null;
      revision: components["schemas"]["RevisionReference"];
      /**
       * Schema Version
       * @default service-v1
       * @constant
       */
      schema_version: "service-v1";
      /** Side Digest */
      side_digest?: string | null;
      /**
       * Task Id
       * Format: uuid
       */
      task_id: string;
    };
    /** HumanTask */
    HumanTask: {
      /** Allowed Responses */
      allowed_responses: components["schemas"]["ResponseAction"][];
      /**
       * Evidence
       * @default []
       */
      evidence: components["schemas"]["SourceCitation"][];
      /** Finding Ids */
      finding_ids: string[];
      kind: components["schemas"]["TaskKind"];
      /** Question */
      question: string;
      required_permission: components["schemas"]["Permission"];
      /** Result Digest */
      result_digest?: string | null;
      run: components["schemas"]["RunReference"];
      /**
       * Schema Version
       * @default service-v1
       * @constant
       */
      schema_version: "service-v1";
      side?: components["schemas"]["FactSideReference"] | null;
      /**
       * State
       * @default open
       * @enum {string}
       */
      state: "open" | "answered" | "superseded";
      /**
       * Task Id
       * Format: uuid
       */
      task_id: string;
      /** Version */
      version: number;
    };
    /**
     * JobAcceptance
     * @description 202 body: acceptance of durable responsibility, never a result or a claim of work.
     *
     *     job_status is pinned so this body can never advertise progress that has not happened.
     *     An idempotent replay of an already-known submission returns JobStatusView instead.
     */
    JobAcceptance: {
      job: components["schemas"]["JobReference"];
      /**
       * Job Status
       * @default queued
       * @constant
       */
      job_status: "queued";
      run: components["schemas"]["RunReference"];
      /**
       * Schema Version
       * @default service-v1
       * @constant
       */
      schema_version: "service-v1";
    };
    /**
     * JobReference
     * @description External job identity. Never carries a queue name, table name or worker identity.
     */
    JobReference: {
      /** Case Id */
      case_id: string;
      /**
       * Job Id
       * Format: uuid
       */
      job_id: string;
      /**
       * Schema Version
       * @default service-v1
       * @constant
       */
      schema_version: "service-v1";
    };
    /**
     * JobStatus
     * @description Durable control-plane status; never interchangeable with wire ExecutionStatus.
     * @enum {string}
     */
    JobStatus:
      | "queued"
      | "dispatched"
      | "running"
      | "waiting_for_human"
      | "retryable_failed"
      | "failed"
      | "succeeded"
      | "cancelled";
    /**
     * JobStatusView
     * @description Authorized status projection: no storage URI, lease owner or dispatch token.
     */
    JobStatusView: {
      /**
       * Attempt Count
       * @default 0
       */
      attempt_count: number;
      /**
       * Cancel Requested
       * @default false
       */
      cancel_requested: boolean;
      current_run?: components["schemas"]["RunReference"] | null;
      job: components["schemas"]["JobReference"];
      job_status: components["schemas"]["JobStatus"];
      /**
       * Open Task Ids
       * @default []
       */
      open_task_ids: string[];
      problem?: components["schemas"]["ServiceProblem"] | null;
      /**
       * Result Version
       * @default 0
       */
      result_version: number;
      /**
       * Schema Version
       * @default service-v1
       * @constant
       */
      schema_version: "service-v1";
    };
    /** MaterialRevision */
    MaterialRevision: {
      /**
       * Canonicalization
       * @default review-material-json-v1
       * @constant
       */
      canonicalization: "review-material-json-v1";
      /**
       * Changes
       * @default []
       */
      changes: components["schemas"]["ValueRevision-Output"][];
      /** Documents */
      documents: components["schemas"]["DocumentReference"][];
      parent?: components["schemas"]["RevisionReference"] | null;
      reference: components["schemas"]["RevisionReference"];
      /** Rules */
      rules: components["schemas"]["RuleReference"][];
      /**
       * Schema Version
       * @default service-v1
       * @constant
       */
      schema_version: "service-v1";
    };
    /** NormalizedValue */
    NormalizedValue: {
      /**
       * Type
       * @enum {string}
       */
      type: "number" | "text" | "category" | "boolean";
      /** Unit */
      unit?: string | null;
      /** Value */
      value: string | number | boolean;
    };
    /**
     * PDFErrorCode
     * @enum {string}
     */
    PDFErrorCode:
      | "unsupported_document_uri"
      | "source_destination_conflict"
      | "pdf_read_error"
      | "pdf_field_placement_error"
      | "pdf_font_error"
      | "pdf_write_error"
      | "invalid_pdf_result";
    /** PDFField */
    PDFField: {
      /** Bounding Box */
      bounding_box: [number, number, number, number];
      /** Field Id */
      field_id: string;
      /** Max Characters */
      max_characters?: number | null;
      /**
       * Operation
       * @default fill_blank
       * @enum {string}
       */
      operation: "fill_blank" | "annotate" | "correct";
      /** Page */
      page: number;
      value_ref?: components["schemas"]["PDFValueRef"] | null;
    };
    /** PDFFieldMap */
    PDFFieldMap: {
      /**
       * Coordinate System
       * @default pdf_bottom_left
       * @constant
       */
      coordinate_system: "pdf_bottom_left";
      /** Fields */
      fields: components["schemas"]["PDFField"][];
      /**
       * Page Numbering
       * @default one_based
       * @constant
       */
      page_numbering: "one_based";
      /**
       * Page Space
       * @default unrotated_crop_box
       * @constant
       */
      page_space: "unrotated_crop_box";
      /** Template Id */
      template_id: string;
    };
    /** PDFProblem */
    PDFProblem: {
      code: components["schemas"]["PDFErrorCode"];
      /**
       * Message
       * @default PDF output failed; review findings remain available.
       * @constant
       */
      message: "PDF output failed; review findings remain available.";
    };
    /**
     * PDFValueRef
     * @description Explicit binding; field_id is a placement ID, never an expression.
     */
    PDFValueRef: {
      /** Comparable Id */
      comparable_id: string;
      /** Factor Id */
      factor_id?: string | null;
      /**
       * Scope
       * @enum {string}
       */
      scope: "regional" | "individual";
      /** Target Id */
      target_id: string;
      /**
       * Value
       * @enum {string}
       */
      value:
        "target_grade" | "comparable_grade" | "adjustment_percent" | "total_adjustment_percent";
    };
    /** PDFWriteResult */
    PDFWriteResult: {
      /**
       * Artifact Created
       * @default true
       */
      artifact_created: boolean;
      /** Output Uri */
      output_uri: string;
      /** Page Count */
      page_count: number;
      /** Warnings */
      warnings?: string[];
      /** Written Field Ids */
      written_field_ids: string[];
    };
    /**
     * Permission
     * @enum {string}
     */
    Permission:
      | "review"
      | "confirm_observation"
      | "correct_material"
      | "approve_rules"
      | "approve_material"
      | "publish_artifact";
    /**
     * PublicValue
     * @description URI-free view of an original/proposed value; never a trusted fact input.
     */
    "PublicValue-Input": {
      /** Confidence */
      confidence?: number | null;
      /**
       * Evidence
       * @default []
       */
      evidence: components["schemas"]["SourceCitation"][];
      /** Raw Text */
      raw_text: string;
      /**
       * Schema Version
       * @default service-v1
       * @constant
       */
      schema_version: "service-v1";
      /**
       * State
       * @enum {string}
       */
      state: "present" | "blank" | "missing" | "not_present" | "not_applicable";
      /** Unit */
      unit?: string | null;
      /** Value */
      value?: components["schemas"]["NormalizedValue"] | string | number | null;
    };
    /**
     * PublicValue
     * @description URI-free view of an original/proposed value; never a trusted fact input.
     */
    "PublicValue-Output": {
      /** Confidence */
      confidence?: number | null;
      /**
       * Evidence
       * @default []
       */
      evidence: components["schemas"]["SourceCitation"][];
      /** Raw Text */
      raw_text: string;
      /**
       * Schema Version
       * @default service-v1
       * @constant
       */
      schema_version: "service-v1";
      /**
       * State
       * @enum {string}
       */
      state: "present" | "blank" | "missing" | "not_present" | "not_applicable";
      /** Unit */
      unit?: string | null;
      /** Value */
      value?: components["schemas"]["NormalizedValue"] | string | null;
    };
    /**
     * ResponseAction
     * @enum {string}
     */
    ResponseAction: "confirm" | "correct" | "reject" | "approve" | "authorize_publication";
    /**
     * ResponseReceipt
     * @description What one accepted response actually committed. Never an approval or a review result.
     *
     *     The receipt is the idempotent body: an exact replay of the same principal, key and
     *     payload returns this same value, so a reviewer who retries a lost response can tell
     *     that their answer landed once rather than twice.
     */
    ResponseReceipt: {
      action: components["schemas"]["ResponseAction"];
      /** Consumed Version */
      consumed_version: number;
      job: components["schemas"]["JobReference"];
      job_status: components["schemas"]["JobStatus"];
      resumed_run?: components["schemas"]["RunReference"] | null;
      revision?: components["schemas"]["RevisionReference"] | null;
      /**
       * Schema Version
       * @default service-v1
       * @constant
       */
      schema_version: "service-v1";
      /**
       * Superseded Task Ids
       * @default []
       */
      superseded_task_ids: string[];
      /**
       * Task Id
       * Format: uuid
       */
      task_id: string;
      /**
       * Task State
       * @default answered
       * @constant
       */
      task_state: "answered";
    };
    /** ReviewFinding */
    ReviewFinding: {
      context?: components["schemas"]["ComparisonContext"] | null;
      /** Evidence */
      evidence?: components["schemas"]["SourceCitation"][];
      /** Expected */
      expected?: string | null;
      /** Factor Id */
      factor_id?: string | null;
      /** Id */
      id: string;
      /** Kind */
      kind: string;
      /** Observed */
      observed?: string | null;
      /** Rule Id */
      rule_id?: string | null;
      /** Rule Version */
      rule_version?: string | null;
      /**
       * Status
       * @enum {string}
       */
      status: "verified" | "needs_review" | "failed";
      /** Trace */
      trace: string;
    };
    /** ReviewResult */
    ReviewResult: {
      /** Case Id */
      case_id: string;
      /** Findings */
      findings: components["schemas"]["Finding"][];
      /** Rule Version */
      rule_version: string;
      /** Schema Version */
      schema_version: string;
    };
    /**
     * ReviewSubmission
     * @description Reserved jobs request; no jobs route or durable implementation in M0.
     */
    ReviewSubmission: {
      /** Documents */
      documents: components["schemas"]["DocumentReference"][];
      /** Idempotency Key */
      idempotency_key: string;
      revision: components["schemas"]["RevisionReference"];
      /**
       * Schema Version
       * @default service-v1
       * @constant
       */
      schema_version: "service-v1";
    };
    /**
     * RevisionListView
     * @description The revision chain this job produced, oldest first and explicitly linked.
     *
     *     The order is part of the contract: a consumer reconstructing what a reviewer changed
     *     must not have to re-sort by a timestamp the service does not publish.
     */
    RevisionListView: {
      job: components["schemas"]["JobReference"];
      /**
       * Revisions
       * @default []
       */
      revisions: components["schemas"]["MaterialRevision"][];
      /**
       * Schema Version
       * @default service-v1
       * @constant
       */
      schema_version: "service-v1";
    };
    /** RevisionReference */
    RevisionReference: {
      /** Case Id */
      case_id: string;
      /** Material Digest */
      material_digest: string;
      /** Revision Id */
      revision_id: string;
      /**
       * Schema Version
       * @default service-v1
       * @constant
       */
      schema_version: "service-v1";
    };
    /**
     * RuleDefinition
     * @description A versioned deterministic validation rule.
     */
    RuleDefinition: {
      /** Description */
      description: string;
      /** Id */
      id: string;
      /** Inputs */
      inputs: string[];
      /**
       * Kind
       * @enum {string}
       */
      kind: "sum" | "equals";
      /**
       * Severity
       * @default error
       * @enum {string}
       */
      severity: "info" | "warning" | "error";
      /** Target */
      target: string;
      /**
       * Tolerance
       * @default 0
       */
      tolerance: number;
    };
    /** RuleReference */
    RuleReference: {
      /** Content Hash */
      content_hash: string;
      context: components["schemas"]["ComparisonContext"];
      /** Rule Set Id */
      rule_set_id: string;
      /**
       * Schema Version
       * @default service-v1
       * @constant
       */
      schema_version: "service-v1";
      /** Version */
      version: string;
    };
    /** RuleSet */
    RuleSet: {
      /**
       * Description
       * @default
       */
      description: string;
      /** Rules */
      rules: components["schemas"]["RuleDefinition"][];
      /** Version */
      version: string;
    };
    /** RunReference */
    RunReference: {
      /** Attempt Id */
      attempt_id?: string | null;
      revision: components["schemas"]["RevisionReference"];
      /**
       * Run Id
       * Format: uuid
       */
      run_id: string;
      /** Runtime Session Id */
      runtime_session_id?: string | null;
      /**
       * Schema Version
       * @default service-v1
       * @constant
       */
      schema_version: "service-v1";
    };
    /**
     * ServiceErrorCode
     * @enum {string}
     */
    ServiceErrorCode:
      | "invalid_request"
      | "unauthorized"
      | "not_found"
      | "version_conflict"
      | "capability_unavailable"
      | "execution_failed";
    /** ServiceProblem */
    ServiceProblem: {
      code: components["schemas"]["ServiceErrorCode"];
      /**
       * Message
       * @default Service operation could not be completed.
       * @constant
       */
      message: "Service operation could not be completed.";
      /**
       * Schema Version
       * @default service-v1
       * @constant
       */
      schema_version: "service-v1";
    };
    /** ServiceResult */
    ServiceResult: {
      /**
       * Artifact Status
       * @default not_requested
       * @enum {string}
       */
      artifact_status:
        "not_requested" | "unavailable" | "unsupported_contexts" | "simulated" | "written";
      /**
       * Artifacts
       * @default []
       */
      artifacts: components["schemas"]["ArtifactManifest"][];
      business_status?: components["schemas"]["WorkflowStatus"] | null;
      /**
       * Durable
       * @default false
       */
      durable: boolean;
      execution_status: components["schemas"]["ExecutionStatus"];
      /**
       * Findings
       * @default []
       */
      findings: components["schemas"]["ReviewFinding"][];
      problem?: components["schemas"]["ServiceProblem"] | null;
      /** Result Version */
      result_version: number;
      run: components["schemas"]["RunReference"];
      /**
       * Schema Version
       * @default service-v1
       * @constant
       */
      schema_version: "service-v1";
      verification?: components["schemas"]["ServiceVerification"] | null;
    };
    /**
     * ServiceVerification
     * @description Sanitized projection of the existing verification report, including preflight.
     */
    ServiceVerification: {
      /**
       * Critical Errors
       * @default []
       */
      critical_errors: components["schemas"]["VerificationDiagnostic"][];
      /**
       * Schema Version
       * @default service-v1
       * @constant
       */
      schema_version: "service-v1";
      status: components["schemas"]["EvaluationStatus"];
      /**
       * Warnings
       * @default []
       */
      warnings: components["schemas"]["VerificationDiagnostic"][];
    };
    /** SourceCitation */
    SourceCitation: {
      /** Bbox */
      bbox: [number, number, number, number];
      /** Content Hash */
      content_hash: string;
      /** Document Id */
      document_id: string;
      /** Excerpt */
      excerpt: string;
      /** Page */
      page: number;
      /** Region Id */
      region_id: string;
      /** Version */
      version: string;
    };
    /**
     * TaskKind
     * @enum {string}
     */
    TaskKind:
      | "fact_confirmation"
      | "material_correction"
      | "rule_approval"
      | "material_approval"
      | "publication_authorization";
    /**
     * TaskListView
     * @description The tasks of one job the caller may act on, ordered oldest first.
     *
     *     Superseded tasks stay listed: a reviewer who is holding a stale task page needs to be
     *     able to discover that it was superseded, rather than to see it silently disappear.
     */
    TaskListView: {
      job: components["schemas"]["JobReference"];
      /**
       * Schema Version
       * @default service-v1
       * @constant
       */
      schema_version: "service-v1";
      /**
       * Tasks
       * @default []
       */
      tasks: components["schemas"]["TaskView"][];
    };
    /**
     * TaskView
     * @description One task plus the names a client would otherwise have to re-derive to answer it.
     *
     *     `subject_id` is the ledger name of the observation the task is about. It is published
     *     rather than left to the caller because deriving it means canonicalizing the comparison
     *     context, and two languages do not canonicalize alike: Python's json.dumps escapes
     *     non-ASCII by default and JavaScript's JSON.stringify does not, so a browser would
     *     compute a different name for any case whose identifiers are not ASCII. Every identifier
     *     in this project's real cases is Chinese.
     */
    TaskView: {
      /**
       * Schema Version
       * @default service-v1
       * @constant
       */
      schema_version: "service-v1";
      /** Subject Id */
      subject_id?: string | null;
      task: components["schemas"]["HumanTask"];
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** ValidationRequest */
    ValidationRequest: {
      case: components["schemas"]["CanonicalCase"];
      rule_set: components["schemas"]["RuleSet"];
    };
    /** ValueRevision */
    "ValueRevision-Input": {
      corrected?: components["schemas"]["PublicValue-Input"] | null;
      corrected_by?: components["schemas"]["ActorReference"] | null;
      original: components["schemas"]["PublicValue-Input"];
      proposed?: components["schemas"]["PublicValue-Input"] | null;
      /**
       * Schema Version
       * @default service-v1
       * @constant
       */
      schema_version: "service-v1";
      /** Subject Id */
      subject_id: string;
    };
    /** ValueRevision */
    "ValueRevision-Output": {
      corrected?: components["schemas"]["PublicValue-Output"] | null;
      corrected_by?: components["schemas"]["ActorReference"] | null;
      original: components["schemas"]["PublicValue-Output"];
      proposed?: components["schemas"]["PublicValue-Output"] | null;
      /**
       * Schema Version
       * @default service-v1
       * @constant
       */
      schema_version: "service-v1";
      /** Subject Id */
      subject_id: string;
    };
    /**
     * VerificationDiagnostic
     * @description Finite public reasons; never carry raw internal verification messages.
     */
    VerificationDiagnostic: {
      /**
       * Code
       * @enum {string}
       */
      code:
        | "source_binding"
        | "source_registry_required"
        | "verification_blocker"
        | "verification_warning";
      /**
       * Message
       * @enum {string}
       */
      message:
        | "Requested documents must match the configured review sources."
        | "A current source registry is required to review the material."
        | "Verification could not pass; inspect review findings or request human review."
        | "Verification reported a warning; request human review before proceeding.";
      /**
       * Schema Version
       * @default service-v1
       * @constant
       */
      schema_version: "service-v1";
    };
    /** VerificationReport */
    VerificationReport: {
      /** Critical Errors */
      critical_errors?: string[];
      status: components["schemas"]["EvaluationStatus"];
      /** Warnings */
      warnings?: string[];
    };
    /**
     * WorkflowStatus
     * @enum {string}
     */
    WorkflowStatus: "received" | "needs_review" | "verified" | "completed" | "failed";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  submit_review_job_v1_review_jobs_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReviewSubmission"];
      };
    };
    responses: {
      /** @description Exact replay of a known submission */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobStatusView"];
        };
      };
      /** @description Durable responsibility accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobAcceptance"];
        };
      };
      /** @description The principal lacks the case permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description No such job for this principal */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description The job is not in a compatible state */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description Invalid submission */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description No durable job store is configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
    };
  };
  read_review_job_v1_review_jobs__job_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobStatusView"];
        };
      };
      /** @description The principal lacks the case permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description No such job for this principal */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description The job is not in a compatible state */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description Invalid submission */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description No durable job store is configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
    };
  };
  cancel_review_job_v1_review_jobs__job_id__cancel_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobStatusView"];
        };
      };
      /** @description The principal lacks the case permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description No such job for this principal */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description The job is not in a compatible state */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description Invalid submission */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description No durable job store is configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
    };
  };
  read_review_job_result_v1_review_jobs__job_id__result_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceResult"];
        };
      };
      /** @description The principal lacks the case permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description No such job for this principal */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description The job is not in a compatible state */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description Invalid submission */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description No durable job store is configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
    };
  };
  list_job_revisions_v1_review_jobs__job_id__revisions_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RevisionListView"];
        };
      };
      /** @description The principal lacks the case permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description No such task or job for this principal */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description The task or revision moved first */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description Invalid response */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description No human-task store is configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
    };
  };
  list_job_tasks_v1_review_jobs__job_id__tasks_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskListView"];
        };
      };
      /** @description The principal lacks the case permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description No such task or job for this principal */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description The task or revision moved first */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description Invalid response */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description No human-task store is configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
    };
  };
  read_task_v1_review_tasks__task_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskView"];
        };
      };
      /** @description The principal lacks the case permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description No such task or job for this principal */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description The task or revision moved first */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description Invalid response */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description No human-task store is configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
    };
  };
  submit_task_response_v1_review_tasks__task_id__responses_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["HumanResponse"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResponseReceipt"];
        };
      };
      /** @description The principal lacks the case permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description No such task or job for this principal */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description The task or revision moved first */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description Invalid response */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
      /** @description No human-task store is configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceProblem"];
        };
      };
    };
  };
  review_v1_reviews_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AgentReviewRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentReviewRun"];
        };
      };
      /** @description Invalid review request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EntryProblemResponse"];
        };
      };
      /** @description Review execution failed */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EntryProblemResponse"];
        };
      };
      /** @description Review service is not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EntryProblemResponse"];
        };
      };
    };
  };
  validate_v1_validate_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ValidationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReviewResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
