/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AddPrivacyRegion */
    AddPrivacyRegion: {
      /**
       * Case Id
       * Format: uuid4
       */
      case_id: string;
      category: components["schemas"]["SensitiveCategory"];
      region: components["schemas"]["PrivacyRegion"];
      /** Revision */
      revision: number;
      /**
       * Schema Version
       * @default local-privacy-v1
       * @constant
       */
      schema_version: "local-privacy-v1";
      /**
       * Snapshot Id
       * Format: uuid4
       */
      snapshot_id: string;
    };
    /** ConfirmPrivacyReview */
    ConfirmPrivacyReview: {
      /**
       * Case Id
       * Format: uuid4
       */
      case_id: string;
      /** Review Digest */
      review_digest: string;
      /** Revision */
      revision: number;
      /**
       * Schema Version
       * @default local-privacy-v1
       * @constant
       */
      schema_version: "local-privacy-v1";
      /**
       * Snapshot Id
       * Format: uuid4
       */
      snapshot_id: string;
    };
    /** EditPrivacyRegion */
    EditPrivacyRegion: {
      /**
       * Candidate Id
       * Format: uuid4
       */
      candidate_id: string;
      /**
       * Case Id
       * Format: uuid4
       */
      case_id: string;
      category: components["schemas"]["SensitiveCategory"];
      /**
       * Entity Id
       * @default null
       */
      entity_id: string | null;
      region: components["schemas"]["PrivacyRegion"];
      /** Revision */
      revision: number;
      /**
       * Schema Version
       * @default local-privacy-v1
       * @constant
       */
      schema_version: "local-privacy-v1";
      /**
       * Snapshot Id
       * Format: uuid4
       */
      snapshot_id: string;
    };
    /** FinalLocalManifest */
    FinalLocalManifest: {
      /**
       * Business Authority
       * @default unchanged
       * @constant
       */
      business_authority: "unchanged";
      /** Byte Size */
      byte_size: number;
      /**
       * Case Id
       * Format: uuid4
       */
      case_id: string;
      /**
       * Document Id
       * Format: uuid4
       */
      document_id: string;
      /**
       * Filename
       * @default final-local.pdf
       * @constant
       */
      filename: "final-local.pdf";
      /** Final Digest */
      final_digest: string;
      /** Input Artifact Digest */
      input_artifact_digest: string;
      /**
       * Map Id
       * Format: uuid4
       */
      map_id: string;
      /** Omitted Fields */
      omitted_fields: string[];
      /** Restored Fields */
      restored_fields: string[];
      /**
       * Revision Id
       * Format: uuid4
       */
      revision_id: string;
      /**
       * Run Id
       * Format: uuid4
       */
      run_id: string;
      /**
       * Schema Version
       * @default local-privacy-v1
       * @constant
       */
      schema_version: "local-privacy-v1";
      /**
       * Signature Effect
       * @default visual_only_no_digital_signature
       * @constant
       */
      signature_effect: "visual_only_no_digital_signature";
      /**
       * State
       * @default refilled_local
       * @constant
       */
      state: "refilled_local";
    };
    /**
     * LocalSourcePage
     * @description Original page transform metadata, retained locally for coordinate mapping.
     */
    LocalSourcePage: {
      /**
       * Coordinate System
       * @default pdf_bottom_left
       * @constant
       */
      coordinate_system: "pdf_bottom_left";
      /** Crop Box */
      crop_box: [number, number, number, number];
      /** Height */
      height: number;
      /** Number */
      number: number;
      /**
       * Page Space
       * @default unrotated_crop_box
       * @constant
       */
      page_space: "unrotated_crop_box";
      /**
       * Rotation
       * @enum {integer}
       */
      rotation: 0 | 90 | 180 | 270;
      /** Width */
      width: number;
    };
    /**
     * LocalSourceSnapshot
     * @description Identity of adapter-owned immutable bytes, not a caller-selected file URI.
     */
    LocalSourceSnapshot: {
      /** Byte Size */
      byte_size: number;
      /**
       * Case Id
       * Format: uuid4
       */
      case_id: string;
      /**
       * Document Id
       * Format: uuid4
       */
      document_id: string;
      /** Pages */
      pages: components["schemas"]["LocalSourcePage"][];
      /**
       * Schema Version
       * @default local-privacy-v1
       * @constant
       */
      schema_version: "local-privacy-v1";
      /**
       * Snapshot Id
       * Format: uuid4
       */
      snapshot_id: string;
      /** Source Digest */
      source_digest: string;
      /** Source Revision */
      source_revision: number;
    };
    /** PageScan */
    PageScan: {
      /**
       * Issues
       * @default []
       */
      issues: components["schemas"]["ScanIssue"][];
      /**
       * Manual Categories
       * @default [
       *       "name",
       *       "identity_number",
       *       "business_number",
       *       "birth_date",
       *       "phone",
       *       "email",
       *       "address",
       *       "account",
       *       "signature",
       *       "stamp",
       *       "face",
       *       "case_contact",
       *       "parcel",
       *       "ownership_financial"
       *     ]
       */
      manual_categories: components["schemas"]["SensitiveCategory"][];
      /**
       * Mode
       * @enum {string}
       */
      mode: "native" | "scanned" | "mixed";
      /**
       * Observations
       * @default []
       */
      observations: components["schemas"]["TextObservation"][];
      /**
       * Ocr Engine Version
       * @default null
       */
      ocr_engine_version: string | null;
      /**
       * Ocr Model Digests
       * @default []
       */
      ocr_model_digests: string[];
      /** Page */
      page: number;
      /**
       * Status
       * @enum {string}
       */
      status: "processed" | "blocked";
    };
    /** PlaceholderOccurrence */
    PlaceholderOccurrence: {
      /**
       * Entity Id
       * Format: uuid4
       */
      entity_id: string;
      /**
       * Occurrence Id
       * Format: uuid4
       */
      occurrence_id: string;
      region: components["schemas"]["PrivacyRegion"];
    };
    /**
     * PrivacyManifest
     * @description Allowlisted sanitized identity only; DTO validity does not permit upload.
     *
     *     IDs must be issued randomly by the future trusted adapter. UUID shape cannot
     *     prove randomness. Repeated entity IDs are legal; occurrence IDs are unique.
     */
    PrivacyManifest: {
      /** Byte Size */
      byte_size: number;
      /**
       * Case Id
       * Format: uuid4
       */
      case_id: string;
      /**
       * Document Id
       * Format: uuid4
       */
      document_id: string;
      /**
       * Filename
       * @default sanitized.pdf
       * @constant
       */
      filename: "sanitized.pdf";
      /**
       * Media Type
       * @default application/pdf
       * @constant
       */
      media_type: "application/pdf";
      /** Occurrences */
      occurrences: components["schemas"]["PlaceholderOccurrence"][];
      /** Pages */
      pages: components["schemas"]["PrivacyPage"][];
      /**
       * Policy Version
       * @default privacy-policy-v1
       * @constant
       */
      policy_version: "privacy-policy-v1";
      /**
       * Processor Version
       * @default privacy-processor-v1
       * @constant
       */
      processor_version: "privacy-processor-v1";
      /** Sanitized Digest */
      sanitized_digest: string;
      /**
       * Schema Version
       * @default privacy-v1
       * @constant
       */
      schema_version: "privacy-v1";
    };
    /** PrivacyPage */
    PrivacyPage: {
      /**
       * Coordinate System
       * @default pdf_bottom_left
       * @constant
       */
      coordinate_system: "pdf_bottom_left";
      /** Height */
      height: number;
      /** Number */
      number: number;
      /**
       * Page Space
       * @default unrotated_crop_box
       * @constant
       */
      page_space: "unrotated_crop_box";
      /** Width */
      width: number;
    };
    /** PrivacyRegion */
    PrivacyRegion: {
      /** Bbox */
      bbox: [number, number, number, number];
      /** Page */
      page: number;
    };
    /**
     * PrivacyReviewCommand
     * @description Local consumer input; no actor, approval, verified flag or workflow state.
     */
    PrivacyReviewCommand: {
      /** Policy Digest */
      policy_digest: string;
      /** Reviewed Pages */
      reviewed_pages: number[];
      /**
       * Schema Version
       * @default local-privacy-v1
       * @constant
       */
      schema_version: "local-privacy-v1";
      /** Selection Revision */
      selection_revision: number;
      /** Selections */
      selections: components["schemas"]["ReviewSelection"][];
      source: components["schemas"]["LocalSourceSnapshot"];
    };
    /** PrivacyReviewEvent */
    PrivacyReviewEvent: {
      /**
       * Action
       * @enum {string}
       */
      action: "scan" | "add" | "edit" | "remove" | "review_page";
      /** @default null */
      after: components["schemas"]["ReviewSelection"] | null;
      /** @default null */
      before: components["schemas"]["ReviewSelection"] | null;
      /**
       * Page
       * @default null
       */
      page: number | null;
      /** Revision */
      revision: number;
      /**
       * Schema Version
       * @default local-privacy-v1
       * @constant
       */
      schema_version: "local-privacy-v1";
    };
    /**
     * PrivacyReviewView
     * @description Only for the trusted local consumer; includes original text and decisions.
     */
    PrivacyReviewView: {
      command: components["schemas"]["PrivacyReviewCommand"];
      /** Events */
      events: components["schemas"]["PrivacyReviewEvent"][];
      scan: components["schemas"]["PrivacyScanReport"] | null;
      /**
       * Schema Version
       * @default local-privacy-v1
       * @constant
       */
      schema_version: "local-privacy-v1";
      /**
       * State
       * @enum {string}
       */
      state: "blocked" | "awaiting_confirmation" | "confirmed";
    };
    /** PrivacyScanReport */
    PrivacyScanReport: {
      /**
       * Candidates
       * @default []
       */
      candidates: components["schemas"]["SensitiveCandidate"][];
      /** Native Engine Version */
      native_engine_version: string;
      /** Pages */
      pages: components["schemas"]["PageScan"][];
      /**
       * Schema Version
       * @default local-privacy-scan-v1
       * @constant
       */
      schema_version: "local-privacy-scan-v1";
      source: components["schemas"]["LocalSourceSnapshot"];
      /**
       * Status
       * @enum {string}
       */
      status: "needs_review" | "blocked";
    };
    /** RemovePrivacyRegion */
    RemovePrivacyRegion: {
      /**
       * Candidate Id
       * Format: uuid4
       */
      candidate_id: string;
      /**
       * Case Id
       * Format: uuid4
       */
      case_id: string;
      /** Reason */
      reason: string;
      /** Revision */
      revision: number;
      /**
       * Schema Version
       * @default local-privacy-v1
       * @constant
       */
      schema_version: "local-privacy-v1";
      /**
       * Snapshot Id
       * Format: uuid4
       */
      snapshot_id: string;
    };
    /** ReviewPrivacyPage */
    ReviewPrivacyPage: {
      /**
       * Case Id
       * Format: uuid4
       */
      case_id: string;
      /** Page */
      page: number;
      /** Revision */
      revision: number;
      /**
       * Schema Version
       * @default local-privacy-v1
       * @constant
       */
      schema_version: "local-privacy-v1";
      /**
       * Snapshot Id
       * Format: uuid4
       */
      snapshot_id: string;
    };
    /**
     * ReviewSelection
     * @description Complete local review set, including explicitly dismissed detections.
     */
    ReviewSelection: {
      candidate: components["schemas"]["SensitiveCandidate"];
      /**
       * Dismissal Reason
       * @default null
       */
      dismissal_reason: string | null;
      /**
       * Disposition
       * @enum {string}
       */
      disposition: "redact" | "dismiss";
      /**
       * Entity Id
       * @default null
       */
      entity_id: string | null;
      /**
       * Schema Version
       * @default local-privacy-v1
       * @constant
       */
      schema_version: "local-privacy-v1";
    };
    /**
     * ScanIssue
     * @enum {string}
     */
    ScanIssue:
      | "ocr_unavailable"
      | "ocr_empty"
      | "ocr_failed"
      | "low_confidence"
      | "processing_timeout"
      | "resource_limit"
      | "invalid_scan_input";
    /** SensitiveCandidate */
    SensitiveCandidate: {
      /**
       * Candidate Id
       * Format: uuid4
       */
      candidate_id: string;
      category: components["schemas"]["SensitiveCategory"];
      /**
       * Confidence
       * @default null
       */
      confidence: number | null;
      /**
       * Crop Id
       * @default null
       */
      crop_id: string | null;
      /** Detector Id */
      detector_id: string;
      /** Detector Version */
      detector_version: string;
      /**
       * Raw Text
       * @default null
       */
      raw_text: string | null;
      region: components["schemas"]["PrivacyRegion"];
      /**
       * Schema Version
       * @default local-privacy-v1
       * @constant
       */
      schema_version: "local-privacy-v1";
    };
    /**
     * SensitiveCategory
     * @enum {string}
     */
    SensitiveCategory:
      | "name"
      | "identity_number"
      | "business_number"
      | "birth_date"
      | "phone"
      | "email"
      | "address"
      | "account"
      | "signature"
      | "stamp"
      | "face"
      | "case_contact"
      | "parcel"
      | "ownership_financial";
    /**
     * TextObservation
     * @description Native block or OCR word; confidence is unmodified, or unknown for native text.
     */
    TextObservation: {
      /**
       * Confidence
       * @default null
       */
      confidence: number | null;
      /**
       * Origin
       * @enum {string}
       */
      origin: "native" | "ocr";
      region: components["schemas"]["PrivacyRegion"];
      /** Text */
      text: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
